theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

author:
  name: "Leonard Berrada"
  avatar: "/assets/images/avatar_small.jpg"
  bio: "Research Scientist @DeepMind." # Note: Markdown is allowed
  location: "London, UK"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lberrada"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/lberrada"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/leonardberrada/"
